
const PACK_VERSION = window.YEAR5_PACK.version;
const CURRENT_USER_KEY = "year5-maths-current-user-" + PACK_VERSION;
const USERS_KEY = "year5-maths-users-" + PACK_VERSION;
function normalise(value){return String(value).toLowerCase().trim().replace(/−/g,"-").replace(/,/g,"").replace(/£/g,"").replace(/\s+/g,"").replace(/²/g,"2").replace(/°c/g,"").replace(/°/g,"").replace(/centimetres|centimeters|centimetre|centimeter/g,"cm").replace(/millilitres|milliliters|millilitre|milliliter/g,"ml").replace(/litres|liters|litre|liter/g,"l").replace(/grams|gram/g,"g").replace(/minutes|minute/g,"min").replace(/pounds|pound/g,"").replace(/about/g,"");}
function safeUserId(name){return name.trim().replace(/\s+/g," ").toLowerCase();}
function getUsers(){try{return JSON.parse(localStorage.getItem(USERS_KEY)||"[]");}catch(e){return[];}}
function saveUser(name){name=name.trim().replace(/\s+/g," ");if(!name)return;const id=safeUserId(name);let users=getUsers();const existing=users.find(u=>u.id===id);if(!existing)users.push({id,name,createdAt:new Date().toISOString()});else existing.name=name;localStorage.setItem(USERS_KEY,JSON.stringify(users));localStorage.setItem(CURRENT_USER_KEY,name);}
function displayName(){return localStorage.getItem(CURRENT_USER_KEY)||"";}
function answerKey(user,pageId){return "year5-maths-answers-"+PACK_VERSION+"::"+safeUserId(user)+"::"+pageId;}
function acceptedSet(item){return new Set(item.accepted.map(normalise));}
function esc(str){return String(str).replace(/[&<>"']/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[s]));}
function pageById(id){return window.YEAR5_PACK.pages.find(p=>p.id===id);}
function renderStudentPage(pageId){const page=pageById(pageId);document.title=page.title+" | Year 5 Maths";document.getElementById("page-title").textContent=page.title;document.getElementById("page-subtitle").textContent="Sign in by name, type your answers, and check your work. This page has "+page.questions.length+" questions.";document.getElementById("objectives").innerHTML=page.objectives.map(o=>"<li>"+esc(o)+"</li>").join("");document.getElementById("mini-lesson").textContent=page.miniLesson;document.getElementById("worked").innerHTML=page.worked.map(w=>"<li>"+esc(w)+"</li>").join("");document.getElementById("total-count").textContent=page.questions.length;document.getElementById("question-heading").textContent=page.id==="final_exam"?"Final exam":"Daily questions";document.getElementById("question-list").innerHTML=page.questions.map((item,idx)=>{const i=idx+1;return `<li class="q-item" id="q${i}"><div class="q-row"><label class="q-label" for="answer-${i}"><span class="q-text">${esc(item.q)}</span></label><input id="answer-${i}" class="answer-input" type="text" inputmode="text" autocomplete="off" placeholder="Type answer" disabled><button type="button" class="check-one" data-qid="${i}" disabled>Check</button></div><div class="feedback" id="feedback-${i}" aria-live="polite"></div></li>`}).join("");setupStudentEvents(page);updateUserUI(page);} 
function getInput(id){return document.getElementById("answer-"+id);} 
function currentAnswerKey(page){const user=displayName();return user?answerKey(user,page.id):null;}
function saveAnswers(page){const key=currentAnswerKey(page);if(!key)return;const data={};page.questions.forEach((item,idx)=>data[idx+1]=getInput(idx+1).value);localStorage.setItem(key,JSON.stringify({updatedAt:new Date().toISOString(),answers:data}));updateAnswered(page);}
function loadAnswers(page){page.questions.forEach((item,idx)=>{const i=idx+1;const input=getInput(i);if(!input)return;input.value="";input.classList.remove("correct","incorrect");const feedback=document.getElementById("feedback-"+i);feedback.textContent="";feedback.className="feedback";});const key=currentAnswerKey(page);if(!key){updateAnswered(page);return;}const raw=localStorage.getItem(key);if(raw){try{const saved=JSON.parse(raw);const data=saved.answers||{};page.questions.forEach((item,idx)=>{const i=idx+1;if(data[i]!==undefined)getInput(i).value=data[i];});}catch(e){}}updateAnswered(page);}
function updateAnswered(page){const answered=page.questions.filter((_,idx)=>getInput(idx+1).value.trim()!=="").length;document.getElementById("answered-count").textContent=answered;}
function checkQuestion(page,id){if(!displayName()){showSignin();return false;}const item=page.questions[id-1];const input=getInput(id);const feedback=document.getElementById("feedback-"+id);input.classList.remove("correct","incorrect");feedback.className="feedback";const value=input.value.trim();if(!value){feedback.textContent="Enter an answer first.";feedback.classList.add("warn");return false;}const ok=acceptedSet(item).has(normalise(value));if(ok){input.classList.add("correct");feedback.textContent="Correct";feedback.classList.add("good");}else{input.classList.add("incorrect");feedback.textContent="Try again";feedback.classList.add("bad");}return ok;}
function checkAll(page){if(!displayName()){showSignin();return;}let correct=0;page.questions.forEach((_,idx)=>{if(checkQuestion(page,idx+1))correct++;});document.getElementById("score-count").textContent=correct;saveAnswers(page);window.scrollTo({top:0,behavior:"smooth"});}
function showSignin(){document.getElementById("signin-box").classList.add("visible");document.getElementById("signin-name").focus();}
function updateUserUI(page){const user=displayName();const signed=Boolean(user);document.getElementById("user-chip").textContent=signed?"Signed in: "+user:"Not signed in";document.getElementById("signin-box").classList.toggle("visible",!signed);document.querySelectorAll(".answer-input, .check-one, #check-all, #reset-page").forEach(el=>el.disabled=!signed);if(signed)loadAnswers(page);else updateAnswered(page);}
function setupStudentEvents(page){document.getElementById("signin-form").onsubmit=e=>{e.preventDefault();saveUser(document.getElementById("signin-name").value);updateUserUI(page);};document.getElementById("switch-user").onclick=()=>{localStorage.removeItem(CURRENT_USER_KEY);loadAnswers(page);updateUserUI(page);showSignin();};document.querySelectorAll(".answer-input").forEach(input=>{input.addEventListener("input",()=>saveAnswers(page));input.addEventListener("keydown",e=>{if(e.key==="Enter"){const id=Number(input.id.replace("answer-",""));checkQuestion(page,id);saveAnswers(page);}});});document.querySelectorAll(".check-one").forEach(btn=>btn.addEventListener("click",()=>{checkQuestion(page,Number(btn.dataset.qid));saveAnswers(page);}));document.getElementById("check-all").onclick=()=>checkAll(page);document.getElementById("reset-page").onclick=()=>{const user=displayName();if(!user)return;if(!confirm("Clear saved answers for "+user+" on this page?"))return;localStorage.removeItem(answerKey(user,page.id));loadAnswers(page);document.getElementById("score-count").textContent="0";};}
function renderIndex(){const cards=window.YEAR5_PACK.pages.map(p=>`<a class="card ${p.id==='final_exam'?'final':''}" href="${p.id==='final_exam'?'final_exam':p.id}.html"><span class="day-num">${p.id==='final_exam'?'Day 7':'Day '+p.id.replace('day','')}</span><strong>${esc(p.title.replace(/^Day \d+: /,''))}</strong><span>${p.questions.length} interactive questions</span></a>`).join("");document.getElementById("cards").innerHTML=cards;const status=()=>{const user=displayName();document.getElementById("user-status").textContent=user?"Signed in: "+user:"Not signed in";};document.getElementById("signin-form").onsubmit=e=>{e.preventDefault();saveUser(document.getElementById("signin-name").value);status();};status();}
function getSavedAnswers(userId,pageId){try{const raw=localStorage.getItem("year5-maths-answers-"+PACK_VERSION+"::"+userId+"::"+pageId);if(!raw)return{};return JSON.parse(raw).answers||{};}catch(e){return{};}}
function renderAdmin(){const userSelect=document.getElementById("user-select"),pageSelect=document.getElementById("page-select");function populate(){const users=getUsers();userSelect.innerHTML=users.length?users.map(u=>`<option value="${esc(u.id)}">${esc(u.name)}</option>`).join(""):'<option value="">No learners found</option>';pageSelect.innerHTML='<option value="all">All pages</option>'+window.YEAR5_PACK.pages.map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join("");}
function rows(){const uid=userSelect.value,filter=pageSelect.value;if(!uid)return[];const pages=filter==='all'?window.YEAR5_PACK.pages:window.YEAR5_PACK.pages.filter(p=>p.id===filter);let out=[];pages.forEach(p=>{const saved=getSavedAnswers(uid,p.id);p.questions.forEach((qu,idx)=>{const qnum=idx+1;const learner=saved[qnum]||"";let status="Blank",cls="status-blank";if(learner.trim()){const ok=acceptedSet(qu).has(normalise(learner));status=ok?"Correct":"Incorrect";cls=ok?"status-correct":"status-wrong";}out.push({page:p.title,qid:qnum,question:qu.q,learner,correct:qu.a,status,cls});});});return out;}
function render(){const rs=rows();let answered=0,correct=0;document.querySelector("#answers-table tbody").innerHTML=rs.map(r=>{if(r.learner.trim())answered++;if(r.status==='Correct')correct++;return `<tr><td class="page-title">${esc(r.page)}</td><td>${r.qid}</td><td>${esc(r.question)}</td><td>${esc(r.learner||'—')}</td><td class="answer">${esc(r.correct)}</td><td class="${r.cls}">${r.status}</td></tr>`;}).join("");document.getElementById("empty-message").textContent=rs.length?"":"No learner data found yet. Ask a learner to sign in and answer questions on this same browser.";document.getElementById("stat-answered").textContent=answered;document.getElementById("stat-correct").textContent=correct;document.getElementById("stat-total").textContent=rs.length;document.getElementById("stat-score").textContent=answered?Math.round(correct/answered*100)+"%":"0%";}
function exportCSV(){const rs=rows();if(!rs.length)return;const header=["Page","Question Number","Question","Learner Answer","Correct Answer","Status"];const csv=[header,...rs.map(r=>[r.page,r.qid,r.question,r.learner,r.correct,r.status])].map(row=>row.map(cell=>'"'+String(cell).replace(/"/g,'""')+'"').join(',')).join('\n');const blob=new Blob([csv],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='year5-maths-results.csv';a.click();URL.revokeObjectURL(url);}
function delUser(){const uid=userSelect.value;if(!uid)return;const name=userSelect.selectedOptions[0]?.textContent||uid;if(!confirm('Delete all saved answers for '+name+'?'))return;window.YEAR5_PACK.pages.forEach(p=>localStorage.removeItem('year5-maths-answers-'+PACK_VERSION+'::'+uid+'::'+p.id));localStorage.setItem(USERS_KEY,JSON.stringify(getUsers().filter(u=>u.id!==uid)));populate();render();}
document.getElementById('refresh-btn').onclick=()=>{populate();render();};document.getElementById('export-btn').onclick=exportCSV;document.getElementById('delete-user-btn').onclick=delUser;userSelect.onchange=render;pageSelect.onchange=render;populate();render();}
